var button1x1 = document.getElementById('button1x1');
var button1x2 = document.getElementById('button1x2');
var button1x3 = document.getElementById('button1x3');
var button1x4 = document.getElementById('button1x4');
var button1x5 = document.getElementById('button1x5');
var button1x6 = document.getElementById('button1x6');
var button1x7 = document.getElementById('button1x7');
var button2x1 = document.getElementById('button2x1');
var button2x2 = document.getElementById('button2x2');
var button2x3 = document.getElementById('button2x3');
var button2x4 = document.getElementById('button2x4');
var button2x5 = document.getElementById('button2x5');
var button2x6 = document.getElementById('button2x6');
var button2x7 = document.getElementById('button2x7');
var button3x1 = document.getElementById('button3x1');
var button3x2 = document.getElementById('button3x2');
var button3x3 = document.getElementById('button3x3');
var button3x4 = document.getElementById('button3x4');
var button3x5 = document.getElementById('button3x5');
var button3x6 = document.getElementById('button3x6');
var button3x7 = document.getElementById('button3x7');
var button4x1 = document.getElementById('button4x1');
var button4x2 = document.getElementById('button4x2');
var button4x3 = document.getElementById('button4x3');
var button4x4 = document.getElementById('button4x4');
var button4x5 = document.getElementById('button4x5');
var button4x6 = document.getElementById('button4x6');
var button4x7 = document.getElementById('button4x7');
var button5x1 = document.getElementById('button5x1');
var button5x2 = document.getElementById('button5x2');
var button5x3 = document.getElementById('button5x3');
var button5x4 = document.getElementById('button5x4');
var button5x5 = document.getElementById('button5x5');
var button5x6 = document.getElementById('button5x6');
var button5x7 = document.getElementById('button5x7');
var button6x1 = document.getElementById('button6x1');
var button6x2 = document.getElementById('button6x2');
var button6x3 = document.getElementById('button6x3');
var button6x4 = document.getElementById('button6x4');
var button6x5 = document.getElementById('button6x5');
var button6x6 = document.getElementById('button6x6');
var button6x7 = document.getElementById('button6x7');

function changeColor(buttonID) {
    ducument.getElementById(buttonID).style.background = '#ff0000';
}

button1x1.addEventListener('click', changeColor(button1x1));
button1x2.addEventListener('click', changeColor(button1x2));
button1x3.addEventListener('click', changeColor);
button1x4.addEventListener('click', changeColor);
button1x5.addEventListener('click', changeColor);
button1x6.addEventListener('click', changeColor);
button1x7.addEventListener('click', changeColor);
button2x1.addEventListener('click', changeColor);
button2x2.addEventListener('click', changeColor);
button2x3.addEventListener('click', changeColor);
button2x4.addEventListener('click', changeColor);
button2x5.addEventListener('click', changeColor);
button2x6.addEventListener('click', changeColor);
button2x7.addEventListener('click', changeColor);
button3x1.addEventListener('click', changeColor);
button3x2.addEventListener('click', changeColor);
button3x3.addEventListener('click', changeColor);
button3x4.addEventListener('click', changeColor);
button3x5.addEventListener('click', changeColor);
button3x6.addEventListener('click', changeColor);
button3x7.addEventListener('click', changeColor);
button4x1.addEventListener('click', changeColor);
button4x2.addEventListener('click', changeColor);
button4x3.addEventListener('click', changeColor);
button4x4.addEventListener('click', changeColor);
button4x5.addEventListener('click', changeColor);
button4x6.addEventListener('click', changeColor);
button4x7.addEventListener('click', changeColor);
button5x1.addEventListener('click', changeColor);
button5x2.addEventListener('click', changeColor);
button5x3.addEventListener('click', changeColor);
button5x4.addEventListener('click', changeColor);
button5x4.addEventListener('click', changeColor);
button5x5.addEventListener('click', changeColor);
button5x6.addEventListener('click', changeColor);
button5x7.addEventListener('click', changeColor);
button6x1.addEventListener('click', changeColor);
button6x2.addEventListener('click', changeColor);
button6x3.addEventListener('click', changeColor);
button6x4.addEventListener('click', changeColor);
button6x5.addEventListener('click', changeColor);
button6x6.addEventListener('click', changeColor);
button6x7.addEventListener('click', changeColor);
